language: ruby
rvm:
  - 1.9.3
  - jruby-19mode
bundler_args: --without development
services: postgresql
before_install:
  - gem update --system 1.8.25 # since ZenTest needs ~> 1.8
  - gem --version
before_script:
  # PostGIS installation stuff from https://github.com/GUI/activerecord-postgis-adapter/blob/545a2856b151172fc3f1b53f26951e5af3d6b0fc/bin/ci/before_install.sh
  # TODO: this could really use some refinement
  - echo "yes" | sudo apt-add-repository ppa:ubuntugis/ubuntugis-unstable
  - sudo apt-get update
  - sudo apt-get install -qq libgeos-dev libproj-dev postgresql-9.1-postgis
  - sudo apt-get install -qq libgeos++-dev

  - |
    cat >config/database.yml <<EOF
    test:
      adapter: postgis
      database: quorum2_test
      username: postgres
      encoding: UTF8
    EOF
  - cp config/config-orig.yml config/config.yml
  - bundle exec rake db:create
  - psql -U postgres -d quorum2_test -c 'CREATE EXTENSION postgis;'
  - bundle exec rake db:schema:load
script: bundle exec rspec && bundle exec cucumber