language: ruby
rvm:
  - 1.9.3
bundler_args: --without development
services: postgresql
before_install:
  - gem update --system 1.8.25 # since ZenTest needs ~> 1.8
  - gem --version
before_script:
  # PostGIS installation stuff from https://github.com/geoalchemy/geoalchemy2/pull/43/files
  # TODO: this could really use some refinement
  - sudo apt-add-repository -y ppa:sharpie/for-science
  - sudo apt-add-repository -y ppa:sharpie/postgis-nightly
  - sudo apt-get update
  - sudo apt-get install postgresql-9.1-postgis -q

  - |
    cat >config/database.yml <<EOF
    test:
      adapter: postgis
      database: quorum2_test
      username: postgres
      encoding: UTF8
    EOF
  - cp config/config-orig.yml config/config.yml
  - bundle exec rake db:create
  - psql -U postgres -d quorum2_test -c 'CREATE EXTENSION postgis;'
  - bundle exec rake db:schema:load
  - |
    cat >config/initializers/secret_token.rb <<EOF
    Quorum2::Application.config.secret_token = '`bundle exec rake secret`'
  - cat config/initializers/secret_token.rb
script: bundle exec rspec -O .rspec.travis && bundle exec cucumber