language: ruby
rvm:
  - 1.9.3
  - jruby-19mode
bundler_args: --without development
services: postgresql
before_install:
  - gem update --system 1.8.25 # since ZenTest needs ~> 1.8
  - gem --version
before_script:
  - |
    cat >config/database.yml <<EOF
    test:
      adapter: postgis
      database: quorum2_test
      username: postgres
      encoding: UTF8
    EOF
  - cp config/config-orig.yml config/config.yml
  - bundle exec rake db:create
  - psql -U postgres -d quorum2_test -c 'CREATE EXTENSION postgis;'
  - bundle exec rake db:schema:load