language: ruby
rvm:
  - 1.9.3
bundler_args: --without development
services: postgresql
before_install:
  - gem update --system 1.8.25 # since ZenTest needs ~> 1.8
  - gem --version
before_script:
  - ./ci/install_postgis.sh
  - ./ci/create_config_files.sh
  - bundle exec rake db:setup_with_postgis
  - |
    cat >config/initializers/secret_token.rb <<EOF
    Quorum2::Application.config.secret_token = '`bundle exec rake secret`'
    EOF
script: bundle exec rspec -O .rspec.travis && bundle exec cucumber