language: ruby
rvm:
  - 1.9.3
  - jruby-19mode
bundler_args: --without development
before_install:
  - gem update --system 1.8.25 # since ZenTest needs ~> 1.8
  - gem --version
script: bundle exec rspec && cucumber