production:
  # Domain on which the site is hosted.
  domain: DOMAIN
  
  # Address that application-generated e-mail will come from.
  email: EMAIL
  
  # SMTP settings for outgoing mail.
  smtp:
    address: SMTP_SERVER_NAME
    port: 25
    user_name: SMTP_USER_NAME
    password: SMTP_PASSWORD
